[project]
org-name = "ballerina"
version = "@toml.version@"

[dependencies]
"ballerina/io" = "@stdlib.io.version@"
"ballerina/stringutils" = "@stdlib.stringutils.version@"
"ballerina/config" = "@stdlib.config.version@"
"ballerina/system" = "@stdlib.system.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "log"
    version = "@project.version@"
    path = "../log-native/build/libs/log-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["log"]

    [[platform.libraries]]
    artifactId = "log"
    version = "@project.version@"
    path = "../log-test-utils/build/libs/log-test-utils-@project.version@.jar"
    groupId = "org.ballerinalang.stdlib.log"
    modules = ["log"]
    scope = "testOnly"
    
