[project]
org-name = "ballerina"
version = "@toml.version@"

[dependencies]
"ballerina/io" = "0.5.0"
"ballerina/stringutils" = "0.5.0"
"ballerina/config" = "1.0.0"
"ballerina/system" = "0.6.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "log"
    version = "@project.version@"
    path = "../log-native/build/libs/log-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["log"]

    [[platform.libraries]]
    artifactId = "log"
    version = "@project.version@"
    path = "../log-test-utils/build/libs/log-test-utils-@project.version@.jar"
    groupId = "org.ballerinalang.stdlib.log"
    modules = ["log"]
    scope = "testOnly"