[package]
org = "ballerina"
name = "log"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "stringutils"
version = "@stdlib.stringutils.version@"
scope = "testOnly"

[[platform.java11.dependency]]
path = "../log-native/build/libs/log-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "log"
version = "@project.version@"

[[platform.java11.dependency]]
path = "../log-test-utils/build/libs/log-test-utils-@project.version@.jar"
groupId = "org.ballerinalang.stdlib.log"
scope = "testOnly"
artifactId = "log"
version = "@project.version@"
